### ISSUE TITLE
Models correspond to some tables

### ISSUE THREAD

**Issue by jackieHubc** [omzmarlon/feedr#10]

**Comment by jackieHubc** [comment]
For example, we need a OrderModel.java for order_info table, etc. 
(So far, we already have OrderModel and UserModel made by @YiyingLin)

**Comment by omzmarlon** [comment]
Issue title should clearly describe the entity/class/task to work on.
If the work is already done we should close it.
I will close this one for now, because it's too vague.
We will open more detailed issues later
