### ISSUE TITLE
User related queries

### ISSUE THREAD

**Issue by omzmarlon** [omzmarlon/feedr#3]
1. create user (sender/receiver) queries
2. get user table queries (username password phone rating etc)
3. update user table queries (username password phone etc)
4. create view (hide password from non-account owner)

Write in UserDAO.java

**Comment by YiyingLin** [comment]
1. creatUser(need values from input)
2. getUser
3. getUsername
4. getUserPhone
5. createUserView(hide password)
6. UpdateUserPhone(username cannot be updated)(need values from input)
(要不要这个功能啊？)
UpdatePassword
7. DeleteUser(need input username to drop table
是不是要这些funcions? 还有补充嘛？
@omzmarlon @jackieHubc @Wennxn

**Comment by omzmarlon** [comment]
For user specifically, I think we need
createUser
getUser (this covers getUsername getPhone )
I don't think we need createUserView, but need a method to get a user's password for logging in: getPassword(username: String): String
and other update functions you mentioned.
and deleteUser by username

**Comment by YiyingLin** [comment]
I realize we can only getUsers or get single user where username = ...
