### ISSUE TITLE
ReceiverDAO

### ISSUE THREAD

**Issue by omzmarlon** [omzmarlon/feedr#5]
1. queries to create instance for order entity
2. queries to update an instance for order entity(change tip, etc)

**Comment by omzmarlon** [comment]
Write OrderDAO.java

**Comment by YiyingLin** [comment]
I accidentally wrote an OrderModel, dont know if it's correct.
It's in the senderOnPublicOrderBoardQuries branch, i pushed it.

**Comment by jackieHubc** [comment]
I just roughly check it and I think it's correct. Thank you for helping! @YiyingLin
