### ISSUE TITLE
CancelDAO

### ISSUE THREAD

**Issue by YiyingLin** [omzmarlon/feedr#8]
Create CancellationDAO and write in it:
1. create CancellationModel
2. getCancellationbyOrderID (pass in order_id and return all attributes) unique
3. cancel an order (create cancellation pass in order_id)
4. My Cancelled Orders History (pass in username and return all attributes)
5. getReason (pass in order_id)
6. Find a user who canceled all his/her orders
7. ...

我觉得我们ui里的那些需要query的东西都比较简单，没有需要join tables啊之类的，这样会不会有影响？
但确实用不到复杂的query e.g. Find the food_name which has a MAX cancellation number?
@omzmarlon

**Comment by omzmarlon** [comment]
最需要的是 给一个username和orderid然后让这个user cancel order
可以先把这个写好pr一下
更复杂的接下来再加
@YiyingLin
